from fastapi import FastAPI, UploadFile, File, Form, BackgroundTasks
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse
from moviepy.editor import VideoFileClip
from supabase import create_client, Client
from pydantic import BaseModel
import shutil
import os
import uuid
import datetime
import time
from services import ai, video, social  # Ensure social.py is updated with the BYOK logic provided previously

# --- CONFIGURATION ---
SUPABASE_URL = os.environ.get("SUPABASE_URL", "https://zasbsaanmlsuytesxmsk.supabase.co")
SUPABASE_KEY = os.environ.get("SUPABASE_KEY", "YOUR_SERVICE_ROLE_KEY")

# Initialize Client
supabase: Client = None
def get_supabase():
    global supabase
    if supabase is None:
        try:
            supabase = create_client(SUPABASE_URL, SUPABASE_KEY)
        except Exception as e:
            print(f"Supabase Init Error: {e}")
    return supabase

# Init immediately
get_supabase()

app = FastAPI()

# --- HEALTH CHECK ---
@app.get("/")
def health_check():
    return {"status": "active", "service": "DirectorFlow Backend"}

# --- CORS ---
origins = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "https://video-saas-1.onrender.com",
    # Add your frontend production URL here when deployed
]

app.add_middleware(
    CORSMiddleware,
    allow_origins=origins,
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

UPLOAD_DIR = "temp_storage"
if not os.path.exists(UPLOAD_DIR): os.makedirs(UPLOAD_DIR)

UI_LOGS = []
def log_ui(msg):
    timestamp = datetime.datetime.now().strftime("%H:%M:%S")
    formatted_msg = f"[{timestamp}] {msg}"
    print(formatted_msg)
    UI_LOGS.append(formatted_msg)
    if len(UI_LOGS) > 50: UI_LOGS.pop(0)

@app.get("/logs")
def get_logs(): return {"logs": UI_LOGS}

@app.get("/gallery/{user_id}")
def get_gallery(user_id: str):
    db = get_supabase()
    try:
        response = db.table("clips").select("*").eq("user_id", user_id).order("created_at", desc=True).execute()
        return response.data
    except Exception as e:
        # Suppress the specific 'ConnectionTerminated' noise
        err_str = str(e)
        if "ConnectionTerminated" not in err_str:
            print(f"DB Error: {err_str}")
        return []

@app.get("/video/{filename}")
def get_video(filename: str):
    path = os.path.join(UPLOAD_DIR, filename)
    if os.path.exists(path): return FileResponse(path)
    return {"error": "File not found"}

# --- AUTH & SOCIAL MEDIA ENDPOINTS (BYOK) ---

class AuthInit(BaseModel):
    user_id: str
    platform: str
    client_id: str
    client_secret: str

class AuthCallback(BaseModel):
    user_id: str
    code: str

@app.post("/auth/init")
def auth_init(data: AuthInit):
    """User submits their keys, we give them a Google URL to authorize"""
    url = social.get_auth_url(data.user_id, data.platform, data.client_id, data.client_secret)
    if url:
        return {"url": url}
    return {"error": "Failed to generate URL"}

@app.post("/auth/callback")
def auth_callback(data: AuthCallback):
    """User finished Google Login, we exchange code for tokens and save them"""
    return social.exchange_code_for_token(data.user_id, data.code)

@app.post("/upload/youtube")
def upload_youtube(
    user_id: str = Form(...),
    video_filename: str = Form(...) 
):
    """
    Uploads a video to the user's connected YouTube channel.
    Note: video_filename should be the full URL or local filename.
    """
    # 1. Resolve File Path
    # Ideally, download from Supabase Storage if it's a URL
    local_path = ""
    
    if "http" in video_filename:
        # It's a URL, download it temporarily
        try:
            import requests
            response = requests.get(video_filename, stream=True)
            temp_name = f"upload_{uuid.uuid4().hex}.mp4"
            local_path = os.path.join(UPLOAD_DIR, temp_name)
            with open(local_path, 'wb') as f:
                for chunk in response.iter_content(chunk_size=8192):
                    f.write(chunk)
        except Exception as e:
            return {"error": f"Failed to download video: {e}"}
    else:
        # Assume it's a local filename in temp_storage (if still exists)
        local_path = os.path.join(UPLOAD_DIR, os.path.basename(video_filename))
    
    if not os.path.exists(local_path):
        return {"error": "Video file not found. Please re-process or use a persistent URL."}

    # 2. Upload
    result = social.upload_video(user_id, local_path, "Viral AI Clip #shorts", "Generated by DirectorFlow")
    
    # 3. Cleanup temp download if we made one
    if "http" in video_filename and os.path.exists(local_path):
        os.remove(local_path)
        
    return result

# --- VIDEO PIPELINE ---

def convert_to_clean_mp4(input_path):
    output_path = input_path.replace(".webm", "_clean.mp4")
    try:
        clip = VideoFileClip(input_path)
        # Use aac codec for better social media compatibility
        clip.write_videofile(output_path, codec='libx264', audio_codec='aac', preset='ultrafast', logger=None)
        clip.close()
        return output_path
    except Exception as e:
        log_ui(f"❌ Conversion Failed: {e}")
        return None

def upload_to_supabase_storage(local_path, destination_name):
    db = get_supabase()
    try:
        with open(local_path, 'rb') as f:
            db.storage.from_("videos").upload(
                path=destination_name,
                file=f,
                file_options={"content-type": "video/mp4"}
            )
        project_id = SUPABASE_URL.split("//")[1].split(".")[0]
        public_url = f"https://{project_id}.supabase.co/storage/v1/object/public/videos/{destination_name}"
        return public_url
    except Exception as e:
        log_ui(f"❌ Storage Upload Error: {e}")
        return None

def process_video_pipeline(raw_file_path, user_id):
    filename = os.path.basename(raw_file_path)
    log_ui(f"⚙️ Processing for User: {user_id[:5]}...")

    clean_video_path = convert_to_clean_mp4(raw_file_path)
    if not clean_video_path: cleanup(raw_file_path); return

    log_ui("🎙️ Transcribing...")
    temp_audio = clean_video_path.replace(".mp4", ".mp3")
    try:
        clip = VideoFileClip(clean_video_path)
        clip.audio.write_audiofile(temp_audio, verbose=False, logger=None)
        clip.close()
        transcript_data = ai.transcribe_audio_groq(temp_audio)
    except Exception as e:
        log_ui(f"❌ Transcribe Error: {e}")
        cleanup(raw_file_path, clean_video_path, temp_audio)
        return

    log_ui("🧠 Analyzing...")
    ai_response = ai.analyze_viral_clips(transcript_data)
    clips_found = ai_response.get('clips', [])
    log_ui(f"✂️ Found {len(clips_found)} clip(s).")

    try:
        final_videos = video.process_video_clips(clean_video_path, ai_response, transcript_data)
        
        for vid_path, title in final_videos:
            local_filename = os.path.basename(vid_path)
            
            log_ui(f"☁️ Uploading {title}...")
            public_url = upload_to_supabase_storage(vid_path, local_filename)
            
            if public_url:
                clip_meta = next((c for c in clips_found if c['title'] == title), None)
                score = clip_meta['score'] if clip_meta else 0
                desc = clip_meta.get('viral_description', "Auto-generated clip")

                data = {
                    "user_id": user_id,
                    "filename": public_url,
                    "title": title,
                    "description": desc,
                    "score": score
                }
                get_supabase().table("clips").insert(data).execute()
                log_ui(f"✅ PUBLISHED: {title}")
                if os.path.exists(vid_path): os.remove(vid_path)
            
    except Exception as e:
        log_ui(f"❌ Edit Error: {e}")
        import traceback
        traceback.print_exc()

    cleanup(raw_file_path, clean_video_path, temp_audio)

def cleanup(*files):
    for f in files:
        if f and os.path.exists(f):
            try: os.remove(f)
            except: pass

@app.post("/upload-chunk") 
async def upload_chunk(
    background_tasks: BackgroundTasks, 
    file: UploadFile = File(...),
    user_id: str = Form(...) 
):
    filename = f"chunk_{uuid.uuid4().hex}.webm"
    file_path = os.path.join(UPLOAD_DIR, filename)
    with open(file_path, "wb") as buffer:
        shutil.copyfileobj(file.file, buffer)
    
    background_tasks.add_task(process_video_pipeline, file_path, user_id)
    return {"status": "received"}